<!doctype html>
<html lang="en-us">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>五Sketchup用ruby进行二次开发创建图形面及pushpullfollowMe方法的应用 | 开发者问答集锦</title>
    <meta property="og:title" content="五Sketchup用ruby进行二次开发创建图形面及pushpullfollowMe方法的应用 - 开发者问答集锦">
    <meta property="og:type" content="article">
        
    <meta property="article:published_time" content='2020-09-02T00:00:00&#43;08:00'>
        
        
    <meta property="article:modified_time" content='2020-09-02T00:00:00&#43;08:00'>
        
    <meta name="Keywords" content="">
    <meta name="description" content="五Sketchup用ruby进行二次开发创建图形面及pushpullfollowMe方法的应用">
        
    <meta name="author" content="">
    <meta property="og:url" content="https://zaina.newban.cn/posts/%E4%BA%94sketchup%E7%94%A8ruby%E8%BF%9B%E8%A1%8C%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%88%9B%E5%BB%BA%E5%9B%BE%E5%BD%A2%E9%9D%A2%E5%8F%8Apushpullfollowme%E6%96%B9%E6%B3%95%E7%9A%84%E5%BA%94%E7%94%A8/">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href='/css/normalize.css'>
    <link rel="stylesheet" href='/css/style.css'>
    <script type="text/javascript" src="//cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    
    
    
    
    
    
</head>


<body>
    <header id="header" class="clearfix">
    <div class="container">
        <div class="col-group">
            <div class="site-name ">
                
                    <a id="logo" href="https://zaina.newban.cn">
                        开发者问答集锦
                    </a>
                
                
            </div>
            <div>
                <nav id="nav-menu" class="clearfix">
                    <a class="" href="https://zaina.newban.cn">首页</a>
                    
                </nav>
            </div>
        </div>
    </div>
</header>

    <div id="body">
        <div class="container">
            <div class="col-group">

                <div class="col-8" id="main">
                    
<div class="res-cons">
    
    <article class="post">
        <header>
            <h1 class="post-title">五Sketchup用ruby进行二次开发创建图形面及pushpullfollowMe方法的应用</h1>
        </header>
        <date class="post-meta meta-date">
            2020年9月2日
        </date>
        
        
        <div class="post-meta">
            <span id="busuanzi_container_page_pv">|<span id="busuanzi_value_page_pv"></span><span>
                    阅读</span></span>
        </div>
        
        
        <div class="post-content">
            <p>在上一节讲到了如何创建直线、曲线、圆及弧线，本节讲如何创建面和使用push/pull和Follow Me方法对面进行推拉创建三维体。</p>

<p><strong>1、创建面</strong></p>

<p>创建面使用的方法是add_face，也是继承于Entities父类。add_face的参数是由一系列用逗号分割开的点或边，下面看看代码如何实现。</p>

<pre><code># 先创建五个点
pt1 = [0, 1, 0]
pt2 = [-0.951, 0.309, 0]
pt3 = [-0.588, -0.809, 0]
pt4 = [ 0.588, -0.809, 0]
pt5 = [ 0.951, 0.309, 0]
# 用这五个点画一个面
pent = Sketchup.active_model.entities.add_face pt1, pt2, pt3,
pt4, pt5
# 打印出这五个点的坐标信息
puts &quot;Point 0: &quot; + pent.vertices[0].position.to_s
puts &quot;Point 1: &quot; + pent.vertices[1].position.to_s
puts &quot;Point 2: &quot; + pent.vertices[2].position.to_s
puts &quot;Point 3: &quot; + pent.vertices[3].position.to_s
</code></pre>

<p>生成的图形就是一个五边形<br />
<a href="https://img.it610.com/image/info8/0605ddb24638494b93a46c7b6bd665ef.jpg"><img src="https://img.it610.com/image/info8/0605ddb24638494b93a46c7b6bd665ef.jpg" alt="五、Sketchup用ruby进行二次开发--
创建图形（面及pushpull、followMe方法的应用）_第1张图片" /></a></p>

<p>特别注意的是点的顺序非常重要，如果把pt2和pt3的顺改变一下，这个图形看起来就不像一个五边形了。但改变点的顺时针方向或逆时针方向是没有关系，依然是五边形。</p>

<p>有趣的是生成的面的正面符合右手定理，即如果点的顺序是顺时针方向，它的正面向量就是（0,0,-1），我可以用代码验证一下。面的方向在push和pull中会用到，稍后讲到。</p>

<pre><code>pent.normal
#输出 (0, 0, -1)
pent.reverse!
pent.normal
#输出 (0, 0, 1)
</code></pre>

<p>** 2、classify_point方法**</p>

<p>classify_point方法用于判断给定的点是否在这个面上，判断方法是通过返回的值，如表所示。</p>

<p>• 0 - 不确定的点<br />
• 1 - 点在面上<br />
• 2 - 点在面的某一条边上<br />
• 4 - 点面的一个顶点</p>

<p>• 8 - 点在面所在的平面上，但不在这个面上<br />
• 16 - 点不在这个面所在的平面上</p>

<p>例如：</p>

<pre><code>face = Sketchup.active_model.entities.add_face [-1, -1, 0], [-1, 1, 0],
[1, 1, 0], [1, -1, 0]
face.classify_point [0, 0, 0]
#输出 1
face.classify_point [1, 1, 0]
#输出 4
face.classify_point [1, 2, 0]
#输出 8
face.classify_point [1, 1, 1]
#输出 16
</code></pre>

<p>** 3、pushpull方法**</p>

<p>这一小节是本节的重点，相信使用过Sketchup的筒子们，肯定特别熟悉推拉工具。face类提供了两个方法把二维面扩展为三维体：pushpull和followme，这跟Sketchup的Push/Pull和Follow
Me工具是一样的。</p>

<p>pushpull非常容易使用和理解，pushpull的参数是一个整数，如果整数是正数，那么就会沿着面的正向量进行拉伸，类似，如果是负数就会沿着反方向拉伸。说到这里不能不说在已有三维体上进行切割功能了，只要在一个三维体指定一个面进行反向拉伸就能将其切除了，要是说的不明白可以看下面这个例子。</p>

<pre><code># Create the box
ent = Sketchup.active_model.entities
main_face = ent.add_face [0,0,0], [6,0,0], [6,8,0], [0,8,0]
main_face.reverse!
main_face.pushpull 5
# Draw a line across the upper-right corner
cut = ent.add_line [6,6,5], [4,8,5]
# Remove the new face
cut.faces[1].pushpull -5
</code></pre>

<p>图1，生成一个四方体</p>

<p><a href="https://img.it610.com/image/info8/36271eace0ff4c66bcef243293793506.jpg"><img src="https://img.it610.com/image/info8/36271eace0ff4c66bcef243293793506.jpg" alt="五、Sketchup用ruby进行二次开发--
创建图形（面及pushpull、followMe方法的应用）_第2张图片" /></a></p>

<p>图2，在顶部生成一条</p>

<p><a href="https://img.it610.com/image/info8/89ca5c44cdce4e92b76fe5cf983b7c23.jpg"><img src="https://img.it610.com/image/info8/89ca5c44cdce4e92b76fe5cf983b7c23.jpg" alt="五、Sketchup用ruby进行二次开发--
创建图形（面及pushpull、followMe方法的应用）_第3张图片" /></a></p>

<p>图3，切去一个角。很神奇吧。</p>

<p><a href="https://img.it610.com/image/info8/019d4339d2c04ed897625e91746fb1e6.jpg"><img src="https://img.it610.com/image/info8/019d4339d2c04ed897625e91746fb1e6.jpg" alt="五、Sketchup用ruby进行二次开发--
创建图形（面及pushpull、followMe方法的应用）_第4张图片" /></a></p>

<p>如果最后一行代码</p>

<pre><code>cut.faces[1].pushpull -5
</code></pre>

<p>把faces[1]变为faces[0],那么图形就变为留下小的那一小部分。</p>

<p>4、followme方法</p>

<p>通过pushpull方法，我们可以沿着正向或反向进行拉伸，这还远远满足不了我们的需求。现在followme方法可以沿着你给定的向量进行扩展。</p>

<p>followme的扩展向量我们成为路径，可以使一条或多条直线，如果是多条直线则需要满足一下两个要求。</p>

<ul>
<li>所有的路径必须是相连的。</li>
</ul>

<p>*要进行拉伸的面不能与路径所在的面重合，这一条非常重要。</p>

<p>下面看例子</p>

<pre><code># Access the Entities container
model = Sketchup.active_model
ent = model.entities
# 创建一个圆面，直径为1英寸
circle = ent.add_circle [0,0,0], [0,0,1], 1
circle_face = ent.add_face circle
# 创建一个正方形的路径
path = ent.add_curve [10,0,0], [10,0,5], [10,5,5],
[10,5,0], [10,0,0]
# Extrude the circle along the path
circle_face.followme path
</code></pre>

<p>生成的图形类似于两个直角的白铁皮烟囱合一块。<br />
<a href="https://img.it610.com/image/info8/b85f695acd7546d3b4b8554eff61a62a.jpg"><img src="https://img.it610.com/image/info8/b85f695acd7546d3b4b8554eff61a62a.jpg" alt="五、Sketchup用ruby进行二次开发--
创建图形（面及pushpull、followMe方法的应用）_第5张图片" /></a></p>

<p>再来看一个例子</p>

<pre><code># Access the Entities object
model = Sketchup.active_model
ents = model.entities
# Create the 2-D shape
curve = ents.add_curve [0, 0, 1.244209], [0.116554, 0, 1.238382],
[0.160261, 0, 1.217985], [0.186486, 0, 1.188846],
[0.1894, 0, 1.165536], [0.17483, 0, 1.145139],
[0.142778, 0, 1.127656], [0.096157, 0, 1.118914],
[0.093243, 0, 1.063551], [0.175152, 0, 0.996269],
[0.175152, 0, 0.915269], [0.28237, 0, 0.871026],
[0.375392, 0, 0.801741], [0.448486, 0, 0.711683],
[0.497151, 0, 0.606398], [0.51839, 0, 0.492371],
[0.510894, 0, 0.376625], [0.475126, 0, 0.26629],
[0.413287, 0, 0.168161], [0.329188, 0, 0.088283],
[0.228007, 0, 0.031575], [0.115978, 0, 0.001531],
[0, 0, 0], [0, 0, 1.244209]
curve_face = ents.add_face curve
# Create the circular path
path = ents.add_circle [0, 0, 0], [0, 0, 1], 2
# Create the figure
curve_face.followme path
</code></pre>

<p>生成的图形为下图所示，这图形比较复杂，大家看看代码也很好理解。</p>

<p><a href="https://img.it610.com/image/info8/6902d9195eae4a3bbf9d6750ea210475.jpg"><img src="https://img.it610.com/image/info8/6902d9195eae4a3bbf9d6750ea210475.jpg" alt="五、Sketchup用ruby进行二次开发--
创建图形（面及pushpull、followMe方法的应用）_第6张图片" /></a></p>

<p>由于这个以后用的比较多，我再来第三个例子吧。</p>

<pre><code># Create the box
ents = Sketchup.active_model.entities
main_face = ents.add_face [0,0,0], [5,0,0], [5,8,0], [0,8,0]
main_face.reverse!
main_face.pushpull 6, true
# Draw a line across a corner
cut = ents.add_line [5, 7, 6], [5, 8, 5]
# Create the chamfer
cut.faces[0].followme main_face.edges
</code></pre>

<p>生成的图形为</p>

<p><a href="https://img.it610.com/image/info8/7f371c11740843b893509ed530a94bf7.jpg"><img src="https://img.it610.com/image/info8/7f371c11740843b893509ed530a94bf7.jpg" alt="五、Sketchup用ruby进行二次开发--
创建图形（面及pushpull、followMe方法的应用）_第7张图片" /></a></p>

<p>好了，今天到这吧，马上凌晨1点了。</p>

        </div>

        


        

<div class="post-archive">
    <h2>See Also</h2>
    <ul class="listing">
        
        <li><a href="/posts/001rubyruby%E4%B8%AD%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F%E5%AE%9E%E4%BE%8B%E5%8F%98%E9%87%8F%E5%B1%80%E9%83%A8%E5%8F%98%E9%87%8F%E7%B1%BB%E5%8F%98%E9%87%8Fsymbol%E5%AF%B9%E6%AF%94/">001rubyRuby中全局变量实例变量局部变量类变量Symbol对比</a></li>
        
        <li><a href="/posts/051rubyonrails%E5%AD%B8%E7%BF%92%E7%AD%86%E8%A8%981hellorails/">051RubyonRails學習筆記1Hellorails</a></li>
        
        <li><a href="/posts/053rubyonrails%E5%AD%B8%E7%BF%92%E7%AD%86%E8%A8%986%E9%87%8D%E6%A7%8B%E5%88%AA%E9%99%A4%E7%95%99%E8%A8%80%E5%AE%89%E5%85%A8/">053RubyonRails學習筆記6重構刪除留言安全</a></li>
        
        <li><a href="/posts/055rubyonrails%E5%AD%B8%E7%BF%92%E7%AD%86%E8%A8%987carrierwaveimplementation/">055RubyonRails學習筆記7CarrierwaveImplementation</a></li>
        
        <li><a href="/posts/065rubyonrails%E7%AD%86%E8%A8%9810showtargetinfoongooglemaps/">065Rubyonrails筆記10showtargetinfoongooglemaps</a></li>
        
    </ul>
</div>


        <div class="post-meta meta-tags">
            
            <ul class="clearfix">
                
                <li><a href='https://zaina.newban.cn/tags/ruby'>ruby</a></li>
                
            </ul>
            
        </div>
    </article>
    
    

    
    
</div>

                    <footer id="footer">
    <div>
        &copy; 2020 <a href="https://zaina.newban.cn">开发者问答集锦 By </a>
        
    </div>
    <br />
    <div>
        <div class="github-badge">
            <a href="https://gohugo.io/" target="_black" rel="nofollow"><span class="badge-subject">Powered by</span><span class="badge-value bg-blue">Hugo</span></a>
        </div>
        <div class="github-badge">
            <a href="https://www.flysnow.org/" target="_black"><span class="badge-subject">Design by</span><span class="badge-value bg-brightgreen">飞雪无情</span></a>
        </div>
        <div class="github-badge">
            <a href="https://github.com/flysnow-org/maupassant-hugo" target="_black"><span class="badge-subject">Theme</span><span class="badge-value bg-yellowgreen">Maupassant</span></a>
        </div>
    </div>
</footer>


    
    <script type="text/javascript">
        window.MathJax = {
            tex2jax: {
                inlineMath: [['$', '$']],
                processEscapes: true
                }
            };
    </script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>

<a id="rocket" href="#top"></a>
<script type="text/javascript" src='/js/totop.js?v=0.0.0' async=""></script>



    <script type="text/javascript" src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js" async></script>




                </div>

                <div id="secondary">
    <section class="widget">
        <form id="search" action='https://zaina.newban.cn/search/' method="get" accept-charset="utf-8" target="_blank" _lpchecked="1">
      
      <input type="text" name="q" maxlength="20" placeholder="Search">
      <input type="hidden" name="sitesearch" value="https://zaina.newban.cn">
      <button type="submit" class="submit icon-search"></button>
</form>
    </section>
    
    <section class="widget">
        <h3 class="widget-title">最近文章</h3>
<ul class="widget-list">
    
    <li>
        <a href="https://zaina.newban.cn/posts/001rubyruby%E4%B8%AD%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F%E5%AE%9E%E4%BE%8B%E5%8F%98%E9%87%8F%E5%B1%80%E9%83%A8%E5%8F%98%E9%87%8F%E7%B1%BB%E5%8F%98%E9%87%8Fsymbol%E5%AF%B9%E6%AF%94/" title="001rubyRuby中全局变量实例变量局部变量类变量Symbol对比">001rubyRuby中全局变量实例变量局部变量类变量Symbol对比</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/007hadoop%E9%9B%86%E7%BE%A4%E9%85%8D%E7%BD%AEhadoop%E9%9B%86%E7%BE%A4%E7%9A%84%E5%90%AF%E5%8A%A8%E5%92%8C%E6%B5%8B%E8%AF%95ssh%E5%85%8D%E7%99%BB%E9%99%86%E9%85%8D%E7%BD%AEstartallshhdfs%E5%B8%B8%E7%94%A8%E7%9A%84shell/" title="007Hadoop集群配置Hadoop集群的启动和测试SSH免登陆配置startallshhdfs常用的shell">007Hadoop集群配置Hadoop集群的启动和测试SSH免登陆配置startallshhdfs常用的shell</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/009shell%E8%84%9A%E6%9C%AC%E4%B8%8B%E6%9D%A1%E4%BB%B6%E6%B5%8B%E8%AF%95eqne/" title="009Shell脚本下条件测试eqne">009Shell脚本下条件测试eqne</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/00pythonmanagepyshell%E5%92%8Cpython%E7%9A%84%E5%88%86%E6%9E%90/" title="00Pythonmanagepyshell和Python的分析">00Pythonmanagepyshell和Python的分析</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/010zookeeper%E7%9A%84%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5zookeeper%E7%9A%84%E9%9B%86%E7%BE%A4%E6%90%AD%E5%BB%BAzookeeper%E7%9A%84shell%E5%91%BD%E4%BB%A4/" title="010Zookeeper的基本概念Zookeeper的集群搭建Zookeeper的shell命令">010Zookeeper的基本概念Zookeeper的集群搭建Zookeeper的shell命令</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/018dockerfileshell/" title="018DockerfileSHELL">018DockerfileSHELL</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/01shell%E5%85%A5%E9%97%A801bashshell%E7%89%B9%E6%80%A7/" title="01Shell入门01bashShell特性">01Shell入门01bashShell特性</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/01shell%E5%8F%98%E9%87%8F/" title="01Shell变量">01Shell变量</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/01shell%E5%9F%BA%E7%A1%80%E6%A6%82%E8%BF%B0%E8%84%9A%E6%9C%AC%E6%89%A7%E8%A1%8C%E6%96%B9%E5%BC%8Fbash%E5%9F%BA%E6%9C%AC%E5%8A%9F%E8%83%BD/" title="01Shell基础概述脚本执行方式Bash基本功能">01Shell基础概述脚本执行方式Bash基本功能</a>
    </li>
    
    <li>
        <a href="https://zaina.newban.cn/posts/01shell%E7%BC%96%E7%A8%8Bhelloworld/" title="01shell编程helloworld">01shell编程helloworld</a>
    </li>
    
</ul>
    </section>

    

    <section class="widget">
        <h3 class="widget-title"><a href="/categories">分类</a></h3>
<ul class="widget-list">
    
</ul>
    </section>

    <section class="widget">
        <h3 class="widget-title"><a href="/tags">标签</a></h3>
<div class="tagcloud">
    
    <a href="https://zaina.newban.cn/tags/ruby/">ruby</a>
    
    <a href="https://zaina.newban.cn/tags/shell/">shell</a>
    
</div>
    </section>

    

    <section class="widget">
        <h3 class="widget-title">其它</h3>
        <ul class="widget-list">
            <li><a href="https://zaina.newban.cn/index.xml">文章 RSS</a></li>
        </ul>
    </section>
</div>
            </div>
        </div>
    </div>
</body>

</html>